export const LOAD_MAPSTYLES_SUCCESS =  'LOAD_MAPSTYLES_SUCCESS';
export const TRACK_MAP_MOVE_SUCCESS =  'TRACK_MAP_MOVE_SUCCESS';
export const SAVE_NEW_STYLE_SUCCESS =  'SAVE_NEW_STYLE_SUCCESS';
export const SAVE_USER_DATA_SUCCESS =  'SAVE_USER_DATA_SUCCESS';
export const CLEAR_USER_DATA_SUCCESS =  'CLEAR_USER_DATA_SUCCESS';
export const TOGGLE_LOGIN_BUTTONS_SUCCESS =  'TOGGLE_LOGIN_BUTTONS_SUCCESS';
export const LOAD_BUTTON_STATE_SUCCESS =  'LOAD_BUTTON_STATE_SUCCESS';
export const DELETE_MAP_STYLE_SUCCESS =  'DELETE_MAP_STYLE_SUCCESS';
