export const LOAD_MAPSTYLES_SUCCESS =  'LOAD_MAPSTYLES_SUCCESS';
export const TRACK_MAP_MOVE_SUCCESS =  'TRACK_MAP_MOVE_SUCCESS';
export const SAVE_NEW_STYLE_SUCCESS =  'SAVE_NEW_STYLE_SUCCESS';
export const SAVE_USER_DATA_SUCCESS =  'SAVE_USER_DATA_SUCCESS';
export const CLEAR_USER_DATA_SUCCESS =  'CLEAR_USER_DATA_SUCCESS';
